//******************************************************************
// 
//  Generated by RoboCompDSL
//  
//  File name: JointMotorPub.ice
//  Source: JointMotorPub.idsl
//
//******************************************************************
#ifndef ROBOCOMPJOINTMOTORPUB_ICE
#define ROBOCOMPJOINTMOTORPUB_ICE
#include <JointMotor.ice>
module RoboCompJointMotorPub
{
	interface JointMotorPub
	{
		void motorStates (RoboCompJointMotor::MotorStateMap mstateMap);
	};
};

#endif
