//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.3
//
// <auto-generated>
//
// Generated from file `BillCoppelia.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#include <BillCoppelia.h>
#include <IceUtil/PushDisableWarnings.h>
#include <Ice/LocalException.h>
#include <Ice/ValueFactory.h>
#include <Ice/OutgoingAsync.h>
#include <Ice/InputStream.h>
#include <Ice/OutputStream.h>
#include <IceUtil/PopDisableWarnings.h>

#if defined(_MSC_VER)
#   pragma warning(disable:4458) // declaration of ... hides class member
#elif defined(__clang__)
#   pragma clang diagnostic ignored "-Wshadow"
#elif defined(__GNUC__)
#   pragma GCC diagnostic ignored "-Wshadow"
#endif

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 307
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 >= 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 3
#       error Ice patch level mismatch!
#   endif
#endif

#ifdef ICE_CPP11_MAPPING // C++11 mapping

namespace
{

const ::std::string iceC_RoboCompBillCoppelia_BillCoppelia_ids[2] =
{
    "::Ice::Object",
    "::RoboCompBillCoppelia::BillCoppelia"
};
const ::std::string iceC_RoboCompBillCoppelia_BillCoppelia_ops[] =
{
    "getPose",
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping",
    "setSpeed",
    "setTarget"
};
const ::std::string iceC_RoboCompBillCoppelia_BillCoppelia_getPose_name = "getPose";
const ::std::string iceC_RoboCompBillCoppelia_BillCoppelia_setSpeed_name = "setSpeed";
const ::std::string iceC_RoboCompBillCoppelia_BillCoppelia_setTarget_name = "setTarget";

}

bool
RoboCompBillCoppelia::BillCoppelia::ice_isA(::std::string s, const ::Ice::Current&) const
{
    return ::std::binary_search(iceC_RoboCompBillCoppelia_BillCoppelia_ids, iceC_RoboCompBillCoppelia_BillCoppelia_ids + 2, s);
}

::std::vector<::std::string>
RoboCompBillCoppelia::BillCoppelia::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector<::std::string>(&iceC_RoboCompBillCoppelia_BillCoppelia_ids[0], &iceC_RoboCompBillCoppelia_BillCoppelia_ids[2]);
}

::std::string
RoboCompBillCoppelia::BillCoppelia::ice_id(const ::Ice::Current&) const
{
    return ice_staticId();
}

const ::std::string&
RoboCompBillCoppelia::BillCoppelia::ice_staticId()
{
    static const ::std::string typeId = "::RoboCompBillCoppelia::BillCoppelia";
    return typeId;
}

/// \cond INTERNAL
bool
RoboCompBillCoppelia::BillCoppelia::_iceD_getPose(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    inS.readEmptyParams();
    Pose ret = this->getPose(current);
    auto ostr = inS.startWriteParams();
    ostr->writeAll(ret);
    inS.endWriteParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
RoboCompBillCoppelia::BillCoppelia::_iceD_setSpeed(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    auto istr = inS.startReadParams();
    float iceP_adv;
    float iceP_rot;
    istr->readAll(iceP_adv, iceP_rot);
    inS.endReadParams();
    this->setSpeed(iceP_adv, iceP_rot, current);
    inS.writeEmptyParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
RoboCompBillCoppelia::BillCoppelia::_iceD_setTarget(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    auto istr = inS.startReadParams();
    float iceP_tx;
    float iceP_ty;
    istr->readAll(iceP_tx, iceP_ty);
    inS.endReadParams();
    this->setTarget(iceP_tx, iceP_ty, current);
    inS.writeEmptyParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
RoboCompBillCoppelia::BillCoppelia::_iceDispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair<const ::std::string*, const ::std::string*> r = ::std::equal_range(iceC_RoboCompBillCoppelia_BillCoppelia_ops, iceC_RoboCompBillCoppelia_BillCoppelia_ops + 7, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - iceC_RoboCompBillCoppelia_BillCoppelia_ops)
    {
        case 0:
        {
            return _iceD_getPose(in, current);
        }
        case 1:
        {
            return _iceD_ice_id(in, current);
        }
        case 2:
        {
            return _iceD_ice_ids(in, current);
        }
        case 3:
        {
            return _iceD_ice_isA(in, current);
        }
        case 4:
        {
            return _iceD_ice_ping(in, current);
        }
        case 5:
        {
            return _iceD_setSpeed(in, current);
        }
        case 6:
        {
            return _iceD_setTarget(in, current);
        }
        default:
        {
            assert(false);
            throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
        }
    }
}
/// \endcond

/// \cond INTERNAL
void
RoboCompBillCoppelia::BillCoppeliaPrx::_iceI_getPose(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<::RoboCompBillCoppelia::Pose>>& outAsync, const ::Ice::Context& context)
{
    _checkTwowayOnly(iceC_RoboCompBillCoppelia_BillCoppelia_getPose_name);
    outAsync->invoke(iceC_RoboCompBillCoppelia_BillCoppelia_getPose_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        nullptr,
        nullptr);
}
/// \endcond

/// \cond INTERNAL
void
RoboCompBillCoppelia::BillCoppeliaPrx::_iceI_setSpeed(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<void>>& outAsync, float iceP_adv, float iceP_rot, const ::Ice::Context& context)
{
    outAsync->invoke(iceC_RoboCompBillCoppelia_BillCoppelia_setSpeed_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        [&](::Ice::OutputStream* ostr)
        {
            ostr->writeAll(iceP_adv, iceP_rot);
        },
        nullptr);
}
/// \endcond

/// \cond INTERNAL
void
RoboCompBillCoppelia::BillCoppeliaPrx::_iceI_setTarget(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<void>>& outAsync, float iceP_tx, float iceP_ty, const ::Ice::Context& context)
{
    outAsync->invoke(iceC_RoboCompBillCoppelia_BillCoppelia_setTarget_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        [&](::Ice::OutputStream* ostr)
        {
            ostr->writeAll(iceP_tx, iceP_ty);
        },
        nullptr);
}
/// \endcond

/// \cond INTERNAL
::std::shared_ptr<::Ice::ObjectPrx>
RoboCompBillCoppelia::BillCoppeliaPrx::_newInstance() const
{
    return ::IceInternal::createProxy<BillCoppeliaPrx>();
}
/// \endcond

const ::std::string&
RoboCompBillCoppelia::BillCoppeliaPrx::ice_staticId()
{
    return BillCoppelia::ice_staticId();
}

namespace Ice
{
}

#else // C++98 mapping

namespace
{

const ::std::string iceC_RoboCompBillCoppelia_BillCoppelia_getPose_name = "getPose";

const ::std::string iceC_RoboCompBillCoppelia_BillCoppelia_setSpeed_name = "setSpeed";

const ::std::string iceC_RoboCompBillCoppelia_BillCoppelia_setTarget_name = "setTarget";

}

/// \cond INTERNAL
::IceProxy::Ice::Object* ::IceProxy::RoboCompBillCoppelia::upCast(BillCoppelia* p) { return p; }

void
::IceProxy::RoboCompBillCoppelia::_readProxy(::Ice::InputStream* istr, ::IceInternal::ProxyHandle< BillCoppelia>& v)
{
    ::Ice::ObjectPrx proxy;
    istr->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new BillCoppelia;
        v->_copyFrom(proxy);
    }
}
/// \endcond

::Ice::AsyncResultPtr
IceProxy::RoboCompBillCoppelia::BillCoppelia::_iceI_begin_getPose(const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    _checkTwowayOnly(iceC_RoboCompBillCoppelia_BillCoppelia_getPose_name, sync);
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_RoboCompBillCoppelia_BillCoppelia_getPose_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_RoboCompBillCoppelia_BillCoppelia_getPose_name, ::Ice::Normal, context);
        result->writeEmptyParams();
        result->invoke(iceC_RoboCompBillCoppelia_BillCoppelia_getPose_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

::RoboCompBillCoppelia::Pose
IceProxy::RoboCompBillCoppelia::BillCoppelia::end_getPose(const ::Ice::AsyncResultPtr& result)
{
    ::Ice::AsyncResult::_check(result, this, iceC_RoboCompBillCoppelia_BillCoppelia_getPose_name);
    ::RoboCompBillCoppelia::Pose ret;
    if(!result->_waitForResponse())
    {
        try
        {
            result->_throwUserException();
        }
        catch(const ::Ice::UserException& ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, ex.ice_id());
        }
    }
    ::Ice::InputStream* istr = result->_startReadParams();
    istr->read(ret);
    result->_endReadParams();
    return ret;
}

::Ice::AsyncResultPtr
IceProxy::RoboCompBillCoppelia::BillCoppelia::_iceI_begin_setSpeed(::Ice::Float iceP_adv, ::Ice::Float iceP_rot, const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_RoboCompBillCoppelia_BillCoppelia_setSpeed_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_RoboCompBillCoppelia_BillCoppelia_setSpeed_name, ::Ice::Normal, context);
        ::Ice::OutputStream* ostr = result->startWriteParams(::Ice::DefaultFormat);
        ostr->write(iceP_adv);
        ostr->write(iceP_rot);
        result->endWriteParams();
        result->invoke(iceC_RoboCompBillCoppelia_BillCoppelia_setSpeed_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

void
IceProxy::RoboCompBillCoppelia::BillCoppelia::end_setSpeed(const ::Ice::AsyncResultPtr& result)
{
    _end(result, iceC_RoboCompBillCoppelia_BillCoppelia_setSpeed_name);
}

::Ice::AsyncResultPtr
IceProxy::RoboCompBillCoppelia::BillCoppelia::_iceI_begin_setTarget(::Ice::Float iceP_tx, ::Ice::Float iceP_ty, const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_RoboCompBillCoppelia_BillCoppelia_setTarget_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_RoboCompBillCoppelia_BillCoppelia_setTarget_name, ::Ice::Normal, context);
        ::Ice::OutputStream* ostr = result->startWriteParams(::Ice::DefaultFormat);
        ostr->write(iceP_tx);
        ostr->write(iceP_ty);
        result->endWriteParams();
        result->invoke(iceC_RoboCompBillCoppelia_BillCoppelia_setTarget_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

void
IceProxy::RoboCompBillCoppelia::BillCoppelia::end_setTarget(const ::Ice::AsyncResultPtr& result)
{
    _end(result, iceC_RoboCompBillCoppelia_BillCoppelia_setTarget_name);
}

/// \cond INTERNAL
::IceProxy::Ice::Object*
IceProxy::RoboCompBillCoppelia::BillCoppelia::_newInstance() const
{
    return new BillCoppelia;
}
/// \endcond

const ::std::string&
IceProxy::RoboCompBillCoppelia::BillCoppelia::ice_staticId()
{
    return ::RoboCompBillCoppelia::BillCoppelia::ice_staticId();
}

RoboCompBillCoppelia::BillCoppelia::~BillCoppelia()
{
}

/// \cond INTERNAL
::Ice::Object* RoboCompBillCoppelia::upCast(BillCoppelia* p) { return p; }

/// \endcond

namespace
{
const ::std::string iceC_RoboCompBillCoppelia_BillCoppelia_ids[2] =
{
    "::Ice::Object",
    "::RoboCompBillCoppelia::BillCoppelia"
};

}

bool
RoboCompBillCoppelia::BillCoppelia::ice_isA(const ::std::string& s, const ::Ice::Current&) const
{
    return ::std::binary_search(iceC_RoboCompBillCoppelia_BillCoppelia_ids, iceC_RoboCompBillCoppelia_BillCoppelia_ids + 2, s);
}

::std::vector< ::std::string>
RoboCompBillCoppelia::BillCoppelia::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&iceC_RoboCompBillCoppelia_BillCoppelia_ids[0], &iceC_RoboCompBillCoppelia_BillCoppelia_ids[2]);
}

const ::std::string&
RoboCompBillCoppelia::BillCoppelia::ice_id(const ::Ice::Current&) const
{
    return ice_staticId();
}

const ::std::string&
RoboCompBillCoppelia::BillCoppelia::ice_staticId()
{
#ifdef ICE_HAS_THREAD_SAFE_LOCAL_STATIC
    static const ::std::string typeId = "::RoboCompBillCoppelia::BillCoppelia";
    return typeId;
#else
    return iceC_RoboCompBillCoppelia_BillCoppelia_ids[1];
#endif
}

/// \cond INTERNAL
bool
RoboCompBillCoppelia::BillCoppelia::_iceD_getPose(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    inS.readEmptyParams();
    Pose ret = this->getPose(current);
    ::Ice::OutputStream* ostr = inS.startWriteParams();
    ostr->write(ret);
    inS.endWriteParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
RoboCompBillCoppelia::BillCoppelia::_iceD_setSpeed(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    ::Ice::InputStream* istr = inS.startReadParams();
    ::Ice::Float iceP_adv;
    ::Ice::Float iceP_rot;
    istr->read(iceP_adv);
    istr->read(iceP_rot);
    inS.endReadParams();
    this->setSpeed(iceP_adv, iceP_rot, current);
    inS.writeEmptyParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
RoboCompBillCoppelia::BillCoppelia::_iceD_setTarget(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    ::Ice::InputStream* istr = inS.startReadParams();
    ::Ice::Float iceP_tx;
    ::Ice::Float iceP_ty;
    istr->read(iceP_tx);
    istr->read(iceP_ty);
    inS.endReadParams();
    this->setTarget(iceP_tx, iceP_ty, current);
    inS.writeEmptyParams();
    return true;
}
/// \endcond

namespace
{
const ::std::string iceC_RoboCompBillCoppelia_BillCoppelia_all[] =
{
    "getPose",
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping",
    "setSpeed",
    "setTarget"
};

}

/// \cond INTERNAL
bool
RoboCompBillCoppelia::BillCoppelia::_iceDispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair<const ::std::string*, const ::std::string*> r = ::std::equal_range(iceC_RoboCompBillCoppelia_BillCoppelia_all, iceC_RoboCompBillCoppelia_BillCoppelia_all + 7, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - iceC_RoboCompBillCoppelia_BillCoppelia_all)
    {
        case 0:
        {
            return _iceD_getPose(in, current);
        }
        case 1:
        {
            return _iceD_ice_id(in, current);
        }
        case 2:
        {
            return _iceD_ice_ids(in, current);
        }
        case 3:
        {
            return _iceD_ice_isA(in, current);
        }
        case 4:
        {
            return _iceD_ice_ping(in, current);
        }
        case 5:
        {
            return _iceD_setSpeed(in, current);
        }
        case 6:
        {
            return _iceD_setTarget(in, current);
        }
        default:
        {
            assert(false);
            throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
        }
    }
}
/// \endcond

/// \cond STREAM
void
RoboCompBillCoppelia::BillCoppelia::_iceWriteImpl(::Ice::OutputStream* ostr) const
{
    ostr->startSlice(ice_staticId(), -1, true);
    ::Ice::StreamWriter< BillCoppelia, ::Ice::OutputStream>::write(ostr, *this);
    ostr->endSlice();
}

void
RoboCompBillCoppelia::BillCoppelia::_iceReadImpl(::Ice::InputStream* istr)
{
    istr->startSlice();
    ::Ice::StreamReader< BillCoppelia, ::Ice::InputStream>::read(istr, *this);
    istr->endSlice();
}
/// \endcond

/// \cond INTERNAL
void
RoboCompBillCoppelia::_icePatchObjectPtr(BillCoppeliaPtr& handle, const ::Ice::ObjectPtr& v)
{
    handle = BillCoppeliaPtr::dynamicCast(v);
    if(v && !handle)
    {
        IceInternal::Ex::throwUOE(BillCoppelia::ice_staticId(), v);
    }
}
/// \endcond

namespace Ice
{
}

#endif
